server {
    listen 80 default_server;
    server_name chretieno.lan _;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
    location / {
        proxy_pass         http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_read_timeout 30s;
    }
}
